### ISSUE TITLE
GLSL GL_ES precision directives yield shader compile errors (Linux)

### ISSUE THREAD

**Issue by bsergean** [stackgl/headless-gl#26] opened 2015-09-08 17:07 UTC
```
THREE.WebGLShader: Shader couldn't compile.
THREE.WebGLShader: gl.getShaderInfoLog() 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER
 1: precision highp float;
2: precision highp int;
```

Even if ANGLE has a shader transpiler that maps ESSL -> conforming GLSL in whatever environment you are running on, this doesn't seem to be working on Linux.

I have tried to strip out such precision directives by removing them from the source in the shaderSource wrapper and the errors go away and my code starts working (yeah), but it feels dirty / gross. I wonder if C++ some code needs to be run to tell ANGLE to transpile the shaders.

Here is the code that does that for reference:

https://github.com/bsergean/headless-gl/commit/92d1f7220979165aa0ae6d6071ee70191f564cea

**Comment by bsergean** [comment] 2015-09-08 17:30
Here's the three.js pull request to wrap precision in #ifdef for reference -> https://github.com/mrdoob/three.js/pull/7136

**Comment by bhouston** [comment] 2015-09-08 17:40
I am not sure ThreeJS should have workarounds for bugs in other people's non-standard implementations of WebGL if they can be avoided?  It isn't my call though.

An alternative solution would be to just monkey patch the ```gl.shaderSource()``` function to look for lines that contain the precision command and insert ifdef/endif before and after them?  Basically do an ( indexOf( 'precision' ) >= 0 ) on the source and if it is found, then convert it into lines via source.split('\n'), run a regex on the lines which are of interest and then insert the ifdefs as appropriate and then .concat('\n') the lines back into a source file.

**Comment by bsergean** [comment] 2015-09-08 17:45
Ah ah, I just did that indeed; monkey-patching the gl.shaderSource and it works.

https://github.com/bsergean/headless-gl/commit/92d1f7220979165aa0ae6d6071ee70191f564cea

It feels a bit dirty though and I'm not sure if would work if multiple instruction are on the same line; can you do that in GLSL ?

    precision foo; precision bar

We could try to do exact matching of all the supported precision, or have a regexp to make this more robust, but it still doesn't feel great.

The downside of monkey-patching is that it could trip some new-comers to the library. This kind of fix could find its way into headless-gl to (which is what I did for now btw), in a nicer fashion. I have a really big dis-taste for #ifdef myself (in C++ code), but in this case it doesn't feel to bad.

**Comment by bsergean** [comment] 2015-09-08 17:47
(btw I didn't really monkey-patch, I just forked headless-gl). I'll see if monkey-patching works.

And yes there will be a maintenance burden to put those #ifdef + I guess that 99% of the use case of three are and will always be in the browser.

Up to you guys.

**Comment by bhouston** [comment] 2015-09-08 17:56
I think you should submit that as a headless-gl PR -- that is the right thing to do in my opinion. :)  Likely help out a lot of others too.

**Comment by bsergean** [comment] 2015-09-08 19:00
Yep I will create a PR there and see what are the thoughts of the headless-gl on the topic. Thanks !

**Comment by mikolalysenko** [comment] 2015-09-12 17:35
This is currently a bug in the linux version of headless-gl.  Somehow the gyp file is misconfigured and not running the angle shader preprocessor correctly. I need to figure that out, but first I want to get all the OS X conformance tests passing.

**Comment by bsergean** [comment] 2015-09-12 17:47
I see. Maybe I’ll take a look at this.

**Comment by bsergean** [comment] 2015-09-13 03:17
Hi, I'm starting to look at this but I have no good ideas on how to proceed. I looked at the gyp file in the angle subfolder, but couldn't find anything obvious. Do you have any hints I could follow to debug this ?

**Comment by bsergean** [comment] 2015-09-13 04:50
Actually it looks like the problem is happening on Mac as well. I have built a recent headless-gl with angle on Mac + Linux, and I am running a modified version of the offscreen_sample.coffee script from this:

https://gist.github.com/bsergean/6780d7cc0cabb1b4d6c8

I have only changed it so that the material is a default three.js one, by overwriting the ShaderMaterial one which works well. Then the problem happens again, on my Mac.

    material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } )

**Comment by bsergean** [comment] 2015-10-06 03:50
Hi there,

Could a patch that removes full lines (see below), or blocks of text which reference precision + all the known precisions (highp, mediump, etc...) with a regexp be incorporated while the better libANGLE fix is being worked out ? Now that 2.1.4 is out I'd like to kill my headless-gl fork and this pb is the only serious one left.

```
diff node_modules/gl/webgl.js vendor/headless-gl/2.1.4/webgl.js
3069,3070c3069,3080
<   source += ''
<   if(!isValidString(source)) {
---
> 
>   var lines = source.split('\n');
>   var N = lines.length;
>   var newLines = [];
>   for (var i = 0; i < N; ++i) {
>     if (lines[i].indexOf('precision') != -1) continue;
>     else newLines.push(lines[i]);
>   }
>   var newSource = newLines.join('\n')
> 
>   newSource += ''
>   if(!isValidString(newSource)) {
3074,3075c3084,3085
<     _shaderSource.call(this, shader._|0, wrapShader(shader._type, source))
<     shader._source = source
---
>     _shaderSource.call(this, shader._|0, wrapShader(shader._type, newSource))
>     shader._source = newSource
```

**Comment by mikolalysenko** [comment] 2015-10-06 16:38
I'm a bit hesitant to merge this in since the shader compilation is still broken.  The real issue here is that ANGLE's shader translator isn't getting run on Linux, which is a serious bug.  I think I can fix this, but I can't look at it in detail until this weekend.

**Comment by bsergean** [comment] 2015-10-06 16:48
Sounds good, no rush for me. I'm using my patched version of webgl.js right now which workaround the pb.

**Comment by mourner** [comment] 2015-10-15 11:43
@mikolalysenko Any luck here? No pressure but very curious!

**Comment by mikolalysenko** [comment] 2015-10-15 12:50
I still haven't gotten it to reproduce locally, and so I haven't started working on a fix yet.  I've tried a couple of Linux distros on parallels, but none so far have manifested with the bug. I might try installing some older ones using virtualbox instead and see if that works.

If anyone has some better ideas here, it would be really helpful.

**Comment by bsergean** [comment] 2015-10-15 16:10
For what it’s worth, I did hit this problem on CentOS 7, and it seemed to be independent of the node.js version. I’m setting up headless-gl on a CentOS 6 now so I’ll be able to report if that problem is happening on this distro as well soon.

**Comment by mikolalysenko** [comment] 2015-10-15 16:25
I tried setting up CentOS 7 on parallels, but the VM wouldn't boot.  Maybe virtualbox would be better, or baring that I'll see if I can spin up a Linode and test it out.

**Comment by bsergean** [comment] 2015-10-15 16:29
I’m using Virtualbox which I got from the Oracle website. On an unrelated note, here’s how I use xvfb-run to run headless programs on Linux. This starts Xvfb on the fly which is very convenient for deployment. I wonder if it should be mentioned somewhere on the headless-gl site / wiki / github as a tip.

xvfb-run -s "-ac -screen 0 1280x1024x24” <regular_program_incantation>

**Comment by mikolalysenko** [comment] 2015-10-15 16:42
Cool, if you send a PR and add that to the README, I'll merge it in.

**Comment by mikolalysenko** [comment] 2016-04-05 17:41
This should be fixed now I think.

**Closed by mikolalysenko** 2016-04-05 17:41 UTC
