### ISSUE TITLE
Intel GPU support

### ISSUE THREAD

**Issue by dariomannu** [stackgl/headless-gl#31] opened 2015-09-15 15:19 UTC
I'm unable to run the example code on an Intel GPU. In this case, it's an `Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)`, running on Linux (Gentoo).

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  28
  Current serial number in output stream:  31
```

Any hope to be able to run this on Intel?

**Comment by mikolalysenko** [comment] 2015-09-15 15:23
This is a duplicate of the following issue:  https://github.com/stackgl/headless-gl/issues/24

Will have this fixed once I get the issues sorted out for node v4 and push a new version.

**Comment by mikolalysenko** [comment] 2015-09-21 17:52
Meanwhile, if you want to get this solved faster comment on this PR:  https://github.com/nodejs/nan/pull/459

**Comment by mikolalysenko** [comment] 2015-09-29 15:33
Workaround in headless-gl@2.1.3

**Closed by mikolalysenko** 2015-09-29 15:33 UTC
